---

# - name: Ensure ownership of Nextcloud directories
#   become: yes
#   ansible.builtin.shell: |
#     chown -R www-data:www-data {{ nextcloud_html_host_path }}
#     chown -R www-data:www-data {{ nextcloud_data_host_path }}
#
# - name: Ensure directory permissions of Nextcloud directories
#   become: yes
#   ansible.builtin.shell: |
#     find {{ nextcloud_html_host_path }} -type d -exec chmod 750 {} \;
#     find {{ nextcloud_data_host_path }} -type d -exec chmod 750 {} \;
#
# - name: Ensure file permissions of Nextcloud directories
#   become: yes
#   ansible.builtin.shell: |
#     find {{ nextcloud_html_host_path }} -type f -exec chmod 640 {} \;
#     find {{ nextcloud_data_host_path }} -type f -exec chmod 640 {} \;

- name: Create directories for nextcloud volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
  loop:
    - "{{ nextcloud_host_path }}/tailscale/config"
    - "{{ nextcloud_host_path }}/tailscale/state"

- name: Create static Tailscale serve configuration
  ansible.builtin.copy:
    dest: "{{ nextcloud_host_path }}/tailscale/config/config.json"
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://127.0.0.1:80"
              }
            }
          }
        },
        "AllowFunnel": {
          "${TS_CERT_DOMAIN}:443": false
        }
      }
    mode: '0644'

- name: Deploy compose template
  ansible.builtin.template:
    src: nextcloud/compose.yml.j2
    dest: "{{ nextcloud_host_path }}/compose.yml"
    mode: '0644'
  notify: "Restart Docker Compose stack"
  vars:
    docker_compose_project_src: "{{ nextcloud_host_path }}"
  register: template_result

- name: Ensure Docker Compose stack is running
  community.docker.docker_compose_v2:
    project_src: "{{ nextcloud_host_path }}"
    state: present
    recreate: "{{ 'always' if force_restart | default(false) else 'never' }}"
  register: compose_output
  async: 30
  poll: 5

- name: Set compose project src fact
  ansible.builtin.set_fact:
    docker_compose_project_src: "{{ nextcloud_host_path }}"
  when: template_result.changed

- name: "Add nextcloud cron"
  tags: "nextcloud"
  become: "yes"
  ansible.builtin.cron:
    name: "start nextcloud cron"
    minute: "5"
    hour: "*"
    job: "docker exec -u www-data nextcloud-app2 php /var/www/html/cron.php"

