---
- name: Check if Docker network exists
  tags: "postgres"
  shell: docker network ls --filter name=^postgres$ --format="{{ '{{.Name}}' }}"
  register: docker_network_ls
  changed_when: docker_network_ls.stdout == ""

- name: Create Docker network
  tags: "postgres"
  command: docker network create postgres
  when: docker_network_ls.stdout == ""

- name: Create directories for postgres volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
  loop:
    - "{{ postgres_host_path }}/tailscale/config"
    - "{{ postgres_host_path }}/tailscale/state"


- name: Create directories for postgres volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 999
    group: 999
  loop:
    - "{{ postgres_host_path }}/data"


- name: Create directories for postgres volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 5050
    group: 1000
  loop:
    - "{{ postgres_host_path }}/pgadmin-data"


- name: Create static Tailscale serve configuration
  ansible.builtin.copy:
    dest: "{{ postgres_host_path }}/tailscale/config/config.json"
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://127.0.0.1:80"
              }
            }
          }
        },
        "AllowFunnel": {
          "${TS_CERT_DOMAIN}:443": false
        }
      }
    mode: '0644'

- name: Deploy compose template
  ansible.builtin.template:
    src: postgres/compose.yml.j2
    dest: "{{ postgres_host_path }}/compose.yml"
    mode: '0644'
  notify: "Restart Docker Compose stack"
  vars:
    docker_compose_project_src: "{{ postgres_host_path }}"
  register: template_result

- name: Ensure Docker Compose stack is running
  community.docker.docker_compose_v2:
    project_src: "{{ postgres_host_path }}"
    state: present
    recreate: "{{ 'always' if force_restart | default(false) else 'never' }}"
  register: compose_output
  async: 30
  poll: 5

- name: Set compose project src fact
  ansible.builtin.set_fact:
    docker_compose_project_src: "{{ postgres_host_path }}"
  when: template_result.changed

